version: '3.1'
services:
  firebase-chatex:
    image: resuelve/phoenix:elixir-1.6.6
    ports:
      - "${VANEX_HOST_PORT:-9000}:4000"
    volumes:
      - ./src:/app/src
      - ./scripts:/scripts
      - ./src/_build/prod/rel:/app/src/_build/prod/rel
      - phx.deps:/app/src/deps
      - phx.builds:/app/src/_build
    depends_on:
      - postgres
    environment:
      - MIX_ENV=${MIX_ENV:-dev}
      - PHX_PORT=${PHX_PORT:-4000}
      - PHX_URL=${PHX_HOST:-localhost}
      - PHX_SECRET_KEY_BASE=${PHX_SECRET_KEY_BASE:-secret}
      - DATABASE_URL=ecto://postgres:postgres@postgres/firebase_chatex_${ENV:-dev}
    working_dir: /app/src
    command: mix phx.server

  postgres:
    image: postgres:9.6

volumes:
  phx.deps:
  phx.builds:
